app_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

# favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    # path('favicon.ico', RedirectView.as_view(url='task_manager/static/notebook.png')),
    path('admin/', admin.site.urls),
    path('', include('task_manager.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "task_manager"
urlpatterns = [
    path('', views.TasksListView.as_view(), name="home-page"),
    path('about', views.AboutPageView.as_view(), name="about-page"),
]

tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "tasks"
urlpatterns = [
    path('add/', views.AddTaskView.as_view(), name="add-task"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-view"),
    path('edit/<int:pk>', views.UpdateTaskView.as_view(), name="edit-task"),
    path('delete/<int:pk>', views.DeleteTaskView.as_view(), name="delete-task"),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "users"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile_update/', views.ProfileUpdateView.as_view(), name="profile-update"),
]

task_manager/models.py
from django.db import models

task_manager/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views import View
from tasks.models import Tasks


class TasksListView(ListView):
    model = Tasks
    template_name = 'task_manager/main_page.html'
    context_object_name = "tasks"

    paginate_by = 5
    ordering = "deadline"

    IMPORTANCE_MAPPING = {
        "high": 3,
        "medium": 2,
        "low": 1,
    }

    def importance_sort_key(self, task, order=None):
        if self.request.session.get('ordering') == "-importance":
            return -self.IMPORTANCE_MAPPING.get(task.importance, 0)
        return self.IMPORTANCE_MAPPING.get(task.importance, 0)

    def get_queryset(self):
        ordering = self.request.session.get('ordering', "deadline")
        queryset = Tasks.objects.filter(author=self.request.user.pk)

        if ordering == "importance" or ordering == "-importance":
            queryset = sorted(queryset, key=self.importance_sort_key)
        else:
            queryset = queryset.order_by(ordering)

        return queryset

    def get(self, request, *args, **kwargs):
        current_ordering = self.request.GET.get('sort')
        if current_ordering:
            if current_ordering == self.request.session.get("ordering"):
                self.request.session["ordering"] = '-' + current_ordering
            else:
                self.request.session["ordering"] = current_ordering
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        return self.render_to_response(context)


class AboutPageView(TemplateView):
    template_name = 'task_manager/about.html'

task_manager/templates/task_manager/about.html
{% extends 'task_manager/base.html' %}
{% block content %}
    <div class="tasks-header-div">
        <h1 class="main-header">About the app</h1>
    </div>

    <div class="about-page-info">
        <p>Django based app written with templates in HTML & CSS</p>
        <p>Currently hosted on linode with linux server</p>
        <p>Check out more of my work on <a href="https://www.github.com/saworz" target="_blank">My Github</a></p>
    </div>
{% endblock %}

task_manager/templates/task_manager/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'task_manager/style.css' %}">
        <title>Task manager</title>
        {% block head %}{% endblock %}
    </head>
    <body>
        <section class="header">
            <nav>
                <div class="navigation-div">
                        <ul>
                            <li><a href="{% url 'task_manager:home-page' %}">Home</a></li>
                            <li><a href="{% url 'task_manager:about-page' %}">About</a></li>

                            {% if user.is_authenticated %}
                                <li><a href="{% url 'tasks:add-task' %}">Add new task</a></li>
                                <li><a href="{% url 'users:profile' %}">My account</a></li>
                                <li><a href="{% url 'users:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'users:login' %}">Login</a></li>
                                <li><a href="{% url 'users:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                </div>
            </nav>
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

task_manager/templates/task_manager/main_page.html
{% extends 'task_manager/base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="tasks-header-div">
            <h1>Active tasks</h1>
        </div>

        <div class="active-tasks-div">
            {% for task in tasks %}
                <a href="{% url 'tasks:task-view' pk=task.pk %}" class="display-task-div">
                    <div class="task-title-div">
                        <h2>{{task.title}}</h2>
                    </div>
                    <div class="task-deadline-div">
                        <p>Deadline: {{task.deadline}}</p>
                    </div>
                    <div class="task-description-div">
                        <p class="description">{{task.description}}</p>
                    </div>
                    <div class="task-deadline-div">
                        <p>Importance: {{task.importance}}</p>
                    </div>
                </a>
            {% endfor %}
        </div>

        <div class="pages-buttons-div">
            {% if is_paginated %}
                  {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                  {% endif %}

                  {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                  {% endif %}
            {% endif %}
        </div>

        {% if tasks %}
            <div class="sorting-text-div">
                <p>Sort by</p>
            </div>

            <div class="sort-buttons-div">
                <form id="sort-form">
                    <button type="radio" name="sort" value="deadline"
                            class="btn btn-primary">Deadline</button>
                    <button type="radio" name="sort" value="title"
                            class="btn btn-primary">Title</button>
                    <button type="radio" name="sort" value="importance"
                            class="btn btn-primary">Importance</button>
                </form>
            </div>
        {% endif %}

    {% else %}
        <div class="tasks-header-div">
            <h1 class="main-header">Task Manager</h1>
        </div>
        <div class="home-page-info">
            <p>Enjoy this super useful app to manage your tasks,</p>
            <p>sort them by importance, deadline or days since created.</p>
        </div>
        <div class="demo-button-div">
            <a href="https://youtu.be/s464OWl58Y8" class="demo-button" target="_blank">Check out the demo</a>
        </div>

    {% endif %}
{% endblock %}