app_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

# favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    # path('favicon.ico', RedirectView.as_view(url='task_manager/static/notebook.png')),
    path('admin/', admin.site.urls),
    path('', include('task_manager.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "tasks"
urlpatterns = [
    path('add/', views.AddTaskView.as_view(), name="add-task"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-view"),
    path('edit/<int:pk>', views.UpdateTaskView.as_view(), name="edit-task"),
    path('delete/<int:pk>', views.DeleteTaskView.as_view(), name="delete-task"),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


IMPORTANCE = {
    ('low', 'LOW'),
    ('medium', 'MEDIUM'),
    ('high', 'HIGH'),
}


class Tasks(models.Model):
    title = models.CharField(max_length=20)
    deadline = models.DateField()
    description = models.TextField()
    importance = models.CharField(max_length=6, choices=IMPORTANCE, default='medium')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('task_manager:home-page')

tasks/forms.py
from django import forms
from .models import Tasks


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = "__all__"

tasks/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime, timedelta
from .forms import AddTaskForm
from .models import Tasks
from django.urls import reverse_lazy


class AddTaskView(LoginRequiredMixin, CreateView):
    template_name = "tasks/add_task.html"
    model = Tasks
    fields = ["title", "deadline", "description", "importance"]

    def get_initial(self):
        initial = super().get_initial()
        initial['deadline'] = (datetime.now() + timedelta(days=7)).strftime('%Y-%m-%d')
        return initial

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdateTaskView(UpdateView):
    model = Tasks
    template_name = "tasks/add_task.html"
    success_url = reverse_lazy("task_manager:home-page")
    fields = ["title", "deadline", "description", "importance"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = True
        return context


class TaskDetailView(DetailView):
    template_name = "tasks/single_task.html"
    model = Tasks


class DeleteTaskView(DeleteView):
    model = Tasks
    success_url = reverse_lazy("task_manager:home-page")

    def get_queryset(self):
        return self.model.objects.filter(pk=self.kwargs["pk"])

    def get_success_url(self):
        return self.success_url

tasks/templates/tasks/add_task.html
{% extends 'task_manager/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'tasks/style.css' %}">
{% endblock %}

{% block content %}
        <div class="tasks-header-div">
            {% if object %}
                <h1>Edit task</h1>
            {% else %}
                <h1>Add task</h1>
            {% endif %}
        </div>

        {% if update %}
            <form action="{% url 'tasks:edit-task' pk=object.pk %}" method="post">
        {% else %}
            <form action="{% url 'tasks:add-task' %}" method="post">
        {% endif %}
        {% csrf_token %}

        {% if object %}
            <div class="edit-task-div">
                <div class="task-title-div">
                    <label for="title"></label>
                    <input type="text" id="title_edit" name="title" value="{{object.title}}">
                </div>

                <div class="task-deadline-div">
                    <label for="deadline"></label>
                    <input type="date" id="deadline_edit" name="deadline" value="{{object.deadline|date:'Y-m-d'}}">
                </div>

                <div class="task-description-div">
                    <label for="description"></label>
                    <textarea id="description_edit" name="description">{{object.description}}</textarea>
                </div>

                <div class="task-importance-div">
                    <p>Importance</p>
                    <div class="radios">
                    <label>
                        {% if object.importance == "low" %}
                            <input type="radio" name="importance" value="low" checked> Low
                        {% else %}
                            <input type="radio" name="importance" value="low"> Low
                        {% endif %}
                    </label>
                    <label>
                        {% if object.importance == "medium" %}
                            <input type="radio" name="importance" value="medium" checked> Medium
                        {% else %}
                            <input type="radio" name="importance" value="medium"> Medium
                        {% endif %}
                    </label>
                    <label>
                        {% if object.importance == "high" %}
                            <input type="radio" name="importance" value="high" checked> High
                        {% else %}
                            <input type="radio" name="importance" value="high"> High
                        {% endif %}
                    </label>
                    </div>
                </div>
            </div>
        {% else %}
             <div class="add-task-div">
                <div class="task-title-div">
                    <label for="title"></label>
                    <input type="text" id="title" name="title" value="Task title">
                </div>

                <div class="task-deadline-div">
                    <label for="deadline"></label>
                    <input type="date" id="deadline" name="deadline" value="{{form.initial.deadline}}">
                </div>

                <div class="task-description-div">
                    <label for="description"></label>
                    <textarea id="description" name="description">That's the place for task description...</textarea>
                </div>

                <div class="task-importance-div">
                    <p>Importance</p>
                    <div class="radios">
                        <label>
                        <input type="radio" name="importance" value="low"> Low
                        </label>
                        <label>
                        <input type="radio" name="importance" value="medium" checked> Medium
                        </label>
                        <label>
                        <input type="radio" name="importance" value="high"> High
                        </label>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="save-task-div">
            <input type="submit" class="demo-button" value="Save task">
        </div>

{% endblock %}

tasks/templates/tasks/single_task.html
{% extends 'task_manager/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'tasks/style.css' %}">
{% endblock %}

{% block content %}
        <div class="tasks-header-div">
            <h1>Task view</h1>
        </div>

        <div class="task-view-div">
            <div class="task-title-div">
                <h2>{{object.title}}</h2>
            </div>
            <div class="task-deadline-div">
                <p>Deadline: {{object.deadline}}</p>
            </div>
            <div class="task-description-div">
                <p class="description">{{object.description}}</p>
            </div>
            <div class="task-deadline-div">
                <p>Importance: {{object.importance}}</p>
            </div>
        </div>

        <div class="task-buttons-div">
            <a href="{% url 'tasks:edit-task' pk=object.pk %}" class="demo-button">Edit task</a>
            <form method="POST" action="{% url 'tasks:delete-task' pk=object.pk %}">
                {% csrf_token %}
                <input type="submit" value="Delete" class="demo-button">
            </form>
        </div>

{% endblock %}