app_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

# favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    # path('favicon.ico', RedirectView.as_view(url='task_manager/static/notebook.png')),
    path('admin/', admin.site.urls),
    path('', include('task_manager.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "tasks"
urlpatterns = [
    path('add/', views.AddTaskView.as_view(), name="add-task"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-view"),
    path('edit/<int:pk>', views.UpdateTaskView.as_view(), name="edit-task"),
    path('delete/<int:pk>', views.DeleteTaskView.as_view(), name="delete-task"),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "users"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile_update/', views.ProfileUpdateView.as_view(), name="profile-update"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['email'].required = False

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        if not username:
            cleaned_data["username"] = self.instance.username
        if not email:
            cleaned_data["email"] = self.instance.email


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


class RegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
        return render(request, 'users/register.html', {'form': form})


class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'users/login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('task_manager:home-page')
        return render(request, 'users/login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('users:login')


class ProfileView(TemplateView):
    template_name = "users/profile.html"


class ProfileUpdateView(View):
    def get(self, request):
        user_form = UserUpdateForm()
        profile_form = ProfileUpdateForm()
        context = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'users/profile_update.html', context)

    def post(self, request):
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:profile')

        context = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'users/profile_update.html',context)

users/templates/users/login.html
{% extends 'task_manager/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
{% endblock %}

{% block content %}
    <div class="form-box">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'task_manager/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-box">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <div class="card">
          <img src="{{user.profile.image.url}}" alt="User" style="width:100%">
          <h1>{{user.username}}</h1>
          <p>{{user.email}}</p>
          <a class="update-button" href="{% url 'users:profile-update' %}">Update profile</a>
        </div>
    </div>
{% endblock %}

users/templates/users/profile_update.html
{% extends 'task_manager/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
{% endblock %}

{% block content %}
    <div class="form-box">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ user_form|crispy }}
              {{ profile_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'task_manager/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
{% endblock %}

{% block content %}
    <div class="form-box">
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Join Today</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Sign Up</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}